; SlowTime — Windows installer (Inno Setup)
; Builds SlowTime-Installer-Windows.exe. Installs the VST3 into the shared
; VST3 folder by default, letting the user pick another location.
;
; Prerequisites (done by CI / the local build step):
;   1. Release VST3 built at ..\build\SlowTime_artefacts\Release\VST3\SlowTime.vst3
;   2. Branding assets generated by installer\make-assets.ps1
; Compile with:  ISCC.exe installer\SlowTime.iss

#define MyAppName "SlowTime"
#define MyAppVersion "0.1.0"
#define MyPublisher "LowHigh Sounds"
#define MyVstSource "..\build\SlowTime_artefacts\Release\VST3\SlowTime.vst3"

[Setup]
AppId={{8F3D2A17-9C4E-4B6A-B1E2-7A5C9D0E4F13}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyPublisher}
AppPublisherURL=https://github.com/lowhighsounds/SlowTime-by-LOWHIGH-SOUNDS
DefaultDirName={commoncf64}\VST3
DisableProgramGroupPage=yes
PrivilegesRequired=admin
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
WizardStyle=modern
SetupIconFile=assets\slowtime.ico
WizardImageFile=assets\wizard-large.bmp
WizardSmallImageFile=assets\wizard-small.bmp
UninstallDisplayIcon={app}\SlowTime.vst3,0
UninstallDisplayName={#MyAppName} (VST3)
OutputDir=output
OutputBaseFilename=SlowTime-Installer-Windows
Compression=lzma2
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Messages]
; Guide the user on the install-location page.
SelectDirLabel3=SlowTime (VST3) will be installed in the folder below. Keep the default so your DAW finds it automatically. If you choose a different folder, remember to add it to your DAW's VST3 search paths.
SelectDirBrowseLabel=To continue, click Next. To pick a different folder, click Browse.

[Files]
; Install the whole SlowTime.vst3 bundle recursively.
Source: "{#MyVstSource}\*"; DestDir: "{app}\SlowTime.vst3"; \
    Flags: recursesubdirs createallsubdirs ignoreversion

[Run]
; Nothing to launch — it's a plugin. (Standalone not shipped.)

[UninstallDelete]
Type: filesandordirs; Name: "{app}\SlowTime.vst3"
