; SlowTime — Windows installer (Inno Setup)
; Builds SlowTime-Installer-Windows.exe. Installs the VST3 and/or CLAP plugin
; into their standard shared folders, chosen via component checkboxes.
;
; Prerequisites (done by CI / the local build step):
;   1. Release builds at ..\build\SlowTime_artefacts\Release\{VST3,CLAP}\
;   2. Branding assets generated by installer\make-assets.ps1
; Compile with:  ISCC.exe installer\SlowTime.iss

#define MyAppName "SlowTime"
#define MyAppVersion "0.1.0"
#define MyPublisher "LowHigh Sounds"
#define MyVst3Source "..\build\SlowTime_artefacts\Release\VST3\SlowTime.vst3"
#define MyClapSource "..\build\SlowTime_artefacts\Release\CLAP\SlowTime.clap"

[Setup]
AppId={{8F3D2A17-9C4E-4B6A-B1E2-7A5C9D0E4F13}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyPublisher}
AppPublisherURL=https://github.com/lowhighsounds/SlowTime-by-LOWHIGH-SOUNDS
; Plugins go to fixed standard folders (per format), so no install directory.
CreateAppDir=no
PrivilegesRequired=admin
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
WizardStyle=modern
SetupIconFile=assets\slowtime.ico
WizardImageFile=assets\wizard-large.bmp
WizardSmallImageFile=assets\wizard-small.bmp
UninstallDisplayIcon={commoncf64}\VST3\SlowTime.vst3,0
UninstallDisplayName={#MyAppName}
OutputDir=output
OutputBaseFilename=SlowTime-Installer-Windows
Compression=lzma2
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Types]
Name: "full";   Description: "All formats (recommended)"
Name: "custom"; Description: "Choose formats"; Flags: iscustom

[Components]
Name: "vst3"; Description: "VST3  —  FL Studio, Ableton, Cubase, Studio One, Reaper, Bitwig, ..."; Types: full custom
Name: "clap"; Description: "CLAP  —  Bitwig, Reaper, FL Studio 2024+, Studio One 6.5+, Cubase 14+";  Types: full custom

[Files]
; VST3 is a bundle (folder) -> install recursively.
Source: "{#MyVst3Source}\*"; DestDir: "{commoncf64}\VST3\SlowTime.vst3"; \
    Components: vst3; Flags: recursesubdirs createallsubdirs ignoreversion
; CLAP on Windows is a single .clap file.
Source: "{#MyClapSource}"; DestDir: "{commoncf64}\CLAP"; \
    Components: clap; Flags: ignoreversion

[UninstallDelete]
Type: filesandordirs; Name: "{commoncf64}\VST3\SlowTime.vst3"
Type: files;          Name: "{commoncf64}\CLAP\SlowTime.clap"
